server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name speedinfer.com www.speedinfer.com 159.54.145.138 _;
    return 301 https://speedinfer.com$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name speedinfer.com www.speedinfer.com 159.54.145.138 _;
    client_max_body_size 500m;

    ssl_certificate /etc/letsencrypt/live/speedinfer.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/speedinfer.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    if ($host != "speedinfer.com") {
        return 301 https://speedinfer.com$request_uri;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_buffering off;
        proxy_cache off;
    }
}

