"""SpeedInfer core authentication, credit metering, and rate-limiting subsystem."""

from speedinfer.core.auth import (
    API_KEY_PREFIX,
    ExpiredApiKeyError,
    InactiveApiKeyError,
    InsufficientScopeError,
    InvalidApiKeyError,
    SpeedInferAuthError,
    authenticate_api_key,
    check_scope_permission,
    check_scopes,
    extract_key_prefix,
    generate_api_key,
    get_authenticated_api_key,
    hash_api_key,
    mask_api_key,
    require_scope,
    verify_api_key,
    verify_api_key_hash,
)
from speedinfer.core.metering import (
    LUA_BALANCE_DEDUCT,
    InsufficientBalanceError,
    async_deduct_balance_atomic,
    calculate_token_cost,
    check_preflight_credit,
    deduct_balance_atomic,
    enforce_preflight_credit,
    estimate_max_cost,
    sync_usage_to_db,
)
from speedinfer.core.rate_limiter import (
    LUA_TOKEN_BUCKET,
    RateLimiter,
    RateLimitResult,
    async_check_rate_limit,
    build_rate_limit_headers,
    check_rate_limit,
    get_rate_limit_headers,
)

__all__ = [
    "API_KEY_PREFIX",
    "ExpiredApiKeyError",
    "InactiveApiKeyError",
    "InsufficientBalanceError",
    "InsufficientScopeError",
    "InvalidApiKeyError",
    "LUA_BALANCE_DEDUCT",
    "LUA_TOKEN_BUCKET",
    "RateLimitResult",
    "RateLimiter",
    "SpeedInferAuthError",
    "async_check_rate_limit",
    "async_deduct_balance_atomic",
    "authenticate_api_key",
    "build_rate_limit_headers",
    "calculate_token_cost",
    "check_preflight_credit",
    "check_rate_limit",
    "check_scope_permission",
    "check_scopes",
    "deduct_balance_atomic",
    "enforce_preflight_credit",
    "estimate_max_cost",
    "extract_key_prefix",
    "generate_api_key",
    "get_authenticated_api_key",
    "get_rate_limit_headers",
    "hash_api_key",
    "mask_api_key",
    "require_scope",
    "sync_usage_to_db",
    "verify_api_key",
    "verify_api_key_hash",
]
